name: women_safety_fyp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.12.2
  carousel_slider: ^4.0.0
  intl: ^0.18.1
  webviewx: ^0.2.1
  flutter_inappwebview: ^5.4.3+7
  lottie: ^2.7.0
  flutter_phone_direct_caller: ^2.1.0
  fluttertoast: ^8.0.9
  url_launcher: ^6.0.20
  flutter_slidable: ^3.0.1
  shared_preferences: ^2.0.13
  pinput: ^3.0.1
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  sizer: ^2.0.15
  image_picker: ^1.0.4
  firebase_storage: ^11.4.1
  cached_network_image: ^3.2.0
  uuid: ^3.0.6
  get: ^4.6.1
  background_sms: ^0.0.4
  permission_handler: ^11.0.1
  flutter_webview_plugin: ^0.4.0
  flutter_spinkit: ^5.1.0
  sqflite: ^2.0.2+1
  contacts_service: ^0.6.3
  geocoding: ^2.0.4
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - images/
